apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rspamd-volatile-keydb
  namespace: {{ .Values.namespace }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.project }}
  sources:
  - repoURL: https://fniko.github.io/keydb-helm-chart/
    chart: keydb
    targetRevision: 1.0.5
    helm:
      valueFiles:
      - $values/custom-values-ext-apps/rspamd-volatile-keydb/{{ .Values.env }}/custom-values.yaml
  - repoURL: https://github.com/tristan-ludlow/app-of-apps.git
    targetRevision: HEAD
    ref: values
  destination:
    server: {{ .Values.dest.cluster }}
    namespace: {{ .Values.dest.namespace }}
